Models basics exercise
marselgabdulov/test_guru pull request #2
Opened 2023-02-28 12:37 UTC by marselgabdulov

Пока не проходили отношения между моделями, поэтому не стал добавлять референсы.

2023-02-28 16:43 UTC, VidgarVii requested changes

2023-02-28 16:43 UTC, VidgarVii commented on db/migrate/20230228120620_change_tests.rb
> +    change_column_null(:tests, :title, false)
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2023-02-28 16:43 UTC, VidgarVii commented on db/schema.rb
> +    t.boolean "correct", default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2023-02-28 16:43 UTC, VidgarVii commented on db/schema.rb
> +  end
на этом задании надо еще добавить связи м/у таблицами. 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true
```

тут мы укажем, что поле должно быть обязательно заполнен и обеспечим ссылочную целостность данных, через внешний ключ
[внешние ключи](https://en.wikipedia.org/wiki/Foreign_key)


Тест принадлежит Категории и Автору
Тест имеет Вопросы
Вопросы имеют Ответы

Вспомни ДЗ про SQL там уже добавляли эти связи

2023-02-28 17:20 UTC, marselgabdulov commented on db/schema.rb
> +  end
Вроде исправил. Тест у меня принадлежит Категории и Пользователю. В будущем пользователи будут делиться по ролям на обычных и администраторов. Администраторы как раз и будут авторами тестов.

2023-03-01 04:06 UTC, VidgarVii requested changes

2023-03-01 04:06 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :user
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали. Тем более они объявлены не верно.
Нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2023-03-01 04:06 UTC, VidgarVii commented on db/migrate/20230228170309_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
При проектировании таблиц надо учитывать смысловую нагрузку.
Лучше если поле в таблице будет называться author_id.
Так как по логике нам надо создать связь теста с юзером как автор теста
т.е. должно получиться
t.references :author... 
Но учти чтоб внешний ключ смотрел на таблицу юзеров
для foreign_key нужно использовать опцию to_table

2023-03-01 04:06 UTC, VidgarVii commented on db/migrate/20230228170705_create_answers.rb
> +      t.references :user, null: false, foreign_key: true
ответы принадлежит только вопросу.

2023-03-01 06:30 UTC, marselgabdulov commented on app/models/answer.rb
> +  belongs_to :user
Эти ассоциации автосгенерированы.

2023-03-01 06:30 UTC, marselgabdulov commented on db/migrate/20230228170309_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
Исправил

2023-03-01 06:30 UTC, marselgabdulov commented on db/migrate/20230228170705_create_answers.rb
> +      t.references :user, null: false, foreign_key: true
Исправил

2023-03-01 07:07 UTC, marselgabdulov commented on app/models/answer.rb
> +  belongs_to :user
Удалил

2023-03-01 14:19 UTC, merged