Scope and validations exercise
marselgabdulov/test_guru pull request #5
Opened 2023-03-08 16:01 UTC by marselgabdulov

2023-03-09 04:06 UTC, VidgarVii requested changes

2023-03-09 04:06 UTC, VidgarVii commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
default_scope` глобально меняет поведение всех запросов к модели
поэтому его [рекомендуют](https://github.com/rubocop-hq/rails-style-guide#macro-style-methods) записывать в самом верху класса

2023-03-09 04:06 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :body, presence: true
вижу валидации не тестировались

2023-03-09 04:06 UTC, VidgarVii commented on app/models/question.rb
> +  validate :answers, length: { minimum: 1, maximum: 4 }
валидация в модели Вопрос не будет препятствовать созданию новых ответов в количестве больше 4, потому что она не будет вызываться при добавлении новых ответов к вопросу

валидации в классе Вопрос вызываются при создании или изменении объектов класса Вопрос
при создании объектов класса Ответ валидации в классе Вопрос не вызываются

2023-03-09 07:46 UTC, marselgabdulov commented on app/models/answer.rb
> +  validate :body, presence: true
Откровенно говоря, я не могу понять о каком тестировании речь, если тестирование мы еще не проходили

2023-03-09 14:57 UTC, VidgarVii requested changes

2023-03-09 14:57 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :body, presence: true
а как 1 блок прошёл?) Там тоже тестирование не проходили. Запускаешь консоль и пробуешь создавать объекты и писать в базу валидные и не валидные данные там. Весь код который пишешь надо проверять. Иначе какой смысл во всём этом?

2023-03-09 14:57 UTC, VidgarVii commented on app/models/answer.rb
> +    errors.add(:questions, "Too much answers!") if question.answers.count > 4
этот метод тоже надо проверить)

2023-03-09 14:59 UTC, marselgabdulov commented on app/models/answer.rb
> +    errors.add(:questions, "Too much answers!") if question.answers.count > 4
Я в первом блоке rspec использовал. Иначе вручную замучаешься все проверять

2023-03-10 06:04 UTC, VidgarVii requested changes

2023-03-10 06:04 UTC, VidgarVii commented on app/models/answer.rb
> +    errors.add(:questions, "Too much answers!") if question.answers.count > 4
большая ошибка считать, что лучше отдать не рабочее ПО, только потому что кто-то замучился всё в ручную проверять.
Валидация не мешает создать больше 4х ответов для вопроса

2023-03-10 15:06 UTC, merged